version: '3.9'
services:
  redis:
    image: sickp/alpine-redis:3.2.2
    container_name: redis
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - redis_network

  backend:
    build: .
    container_name: django-dev
    restart: always
    depends_on:
    #   - bitcoind-dev
    #   - lnd-dev
      - redis
    environment:
      DEVELOPMENT: 1
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database
    networks:
      - nginx_network
      - redis_network
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    container_name: npm-dev
    restart: always
    volumes:
      - .:/usr/src/robosats
    networks:
      - nginx_network
      - redis_network

  clean-orders:
    build: .
    restart: always
    container_name: clord-dev
    command: python3 manage.py clean_orders
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database

  follow-invoices:
    build: .
    container_name: invo-dev
    restart: always
    # depends_on:
    #   - bitcoind-testnet
    #   - lnd-testnet
    command: python3 manage.py follow_invoices
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database

  celery:
    build: .
    container_name: cbeat-dev
    restart: always
    command: celery -A robosats worker --beat -l info -S django
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database
    depends_on:
      - redis
    networks:
      - redis_network

volumes:
  redisdata:

networks:
  nginx_network:
    driver: bridge
  redis_network:
    driver: bridge