version: '3.9'
services:
  redis:
    image: sickp/alpine-redis:3.2.2
    container_name: redis
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - redis_network

  backend:
    build: .
    container_name: django-dev
    restart: always
    depends_on:
      - bitcoind
    #   - lnd-dev
      - redis
    environment:
      DEVELOPMENT: 1
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database
    networks:
      - nginx_network
      - redis_network
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    build: ./frontend
    container_name: npm-dev
    restart: always
    volumes:
      - ./frontend:/usr/src/frontend
    networks:
      - nginx_network
      - redis_network

  clean-orders:
    build: .
    restart: always
    container_name: clord-dev
    command: python3 manage.py clean_orders
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database

  follow-invoices:
    build: .
    container_name: invo-dev
    restart: always
    depends_on:
      - bitcoind
    #   - lnd-testnet
    command: python3 manage.py follow_invoices
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database

  celery:
    build: .
    container_name: cbeat-dev
    restart: always
    command: celery -A robosats worker --beat -l info -S django
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/usr/src/robosats
      - /mnt/development/database:/usr/src/database
    depends_on:
      - redis
    networks:
      - redis_network

  tor:
    build: ./docker/tor
    container_name: tor-dev
    restart: always
    environment:
      LOCAL_USER_ID: 1000
      LOCAL_GROUP_ID: 1000
    volumes:
      - /mnt/development/tor/data:/var/lib/tor
      - /mnt/development/tor/config:/etc/tor
    ports:
      - '10009'
      - '8080'

  lnd:
    build: ./docker/lnd
    restart: always
    network_mode: service:tor
    container_name: lnd-dev
    depends_on:
      - tor
      - bitcoind
    volumes:
      - /mnt/development/tor/data:/var/lib/tor
      - /mnt/development/tor/config:/etc/tor
      - /mnt/development/lnd:/home/lnd/.lnd
      - /mnt/development/lnd:/root/.lnd
    command: lnd
    environment:
      LOCAL_USER_ID: 1000
      LOCAL_GROUP_ID: 1000
      LND_RPC_PORT: 10009
      LND_REST_PORT: 8080

  bitcoind:
    build: ./docker/bitcoind
    container_name: btc-dev
    restart: always
    environment:
      LOCAL_USER_ID: 1000
      LOCAL_GROUP_ID: 1000
    depends_on:
      - tor
    network_mode: service:tor
    volumes:
      - /mnt/development/tor/data:/var/lib/tor:ro
      - /mnt/development/tor/config:/etc/tor:ro
      - /mnt/development/bitcoin:/home/bitcoin/.bitcoin

volumes:
  redisdata:

networks:
  nginx_network:
    driver: bridge
  redis_network:
    driver: bridge